// <auto-generated />
namespace WebApi2StarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_required_Tenant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_required_Tenant));
        
        string IMigrationMetadata.Id
        {
            get { return "201702220227567_remove_required_Tenant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
