// <auto-generated />
namespace WebApi2StarterKit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_UserName_UniqueIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_UserName_UniqueIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201702070720377_Update_UserName_UniqueIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
